// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package database

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
	author,
	body,
	created_at,
	updated_at,
	post_id
)
VALUES (
	$1,
	$2,
	NOW(),
	NOW(),
	$3
)
RETURNING id, author, body, created_at, updated_at, post_id
`

type CreateCommentParams struct {
	Author string
	Body   string
	PostID int32
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.Author, arg.Body, arg.PostID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostID,
	)
	return i, err
}

const deleteCommentByID = `-- name: DeleteCommentByID :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteCommentByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCommentByID, id)
	return err
}

const getAllComments = `-- name: GetAllComments :many
SELECT id, author, body, created_at, updated_at, post_id
FROM comments
`

func (q *Queries) GetAllComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getAllComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, author, body, created_at, updated_at, post_id
FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id int32) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostID,
	)
	return i, err
}

const getPostComments = `-- name: GetPostComments :many
SELECT id, author, body, created_at, updated_at, post_id
FROM comments
WHERE post_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPostComments(ctx context.Context, postID int32) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getPostComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PostID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET
	author = $2,
	body = $3,
	update_at = NOW()
WHERE id = $1
`

type UpdateCommentParams struct {
	ID     int32
	Author string
	Body   string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.ID, arg.Author, arg.Body)
	return err
}
