// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Comment struct {
	ID        int32
	Author    string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	PostID    int32
}

type Post struct {
	ID        int32
	SlugTitle string
	Title     string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Tags      []string
}
