// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
	slug_title,
	title,
	body,
	created_at,
	updated_at,
	tags
)
VALUES(
	$1,
	$2,
	$3,
	NOW(),
	NOW(),
	$4
)
RETURNING id, slug_title, title, body, created_at, updated_at, tags
`

type CreatePostParams struct {
	SlugTitle string
	Title     string
	Body      string
	Tags      []string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.SlugTitle,
		arg.Title,
		arg.Body,
		pq.Array(arg.Tags),
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SlugTitle,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const deletePostByID = `-- name: DeletePostByID :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePostByID(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePostByID, id)
	return err
}

const deletePostBySlugTitle = `-- name: DeletePostBySlugTitle :exec
DELETE FROM posts
WHERE slug_title = $1
`

func (q *Queries) DeletePostBySlugTitle(ctx context.Context, slugTitle string) error {
	_, err := q.db.ExecContext(ctx, deletePostBySlugTitle, slugTitle)
	return err
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT id, slug_title, title, body, created_at, updated_at, tags
FROM posts
ORDER BY created_at DESC
`

func (q *Queries) GetAllPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.SlugTitle,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.Tags),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, slug_title, title, body, created_at, updated_at, tags
FROM posts
WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SlugTitle,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const getPostBySlugTitle = `-- name: GetPostBySlugTitle :one
SELECT id, slug_title, title, body, created_at, updated_at, tags
FROM posts
WHERE slug_title = $1
`

func (q *Queries) GetPostBySlugTitle(ctx context.Context, slugTitle string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostBySlugTitle, slugTitle)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.SlugTitle,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Tags),
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET
	slug_title = $2,
	title = $3,
	body = $4,
	update_at = NOW(),
	tags = $5
WHERE id = $1
`

type UpdatePostParams struct {
	ID        int32
	SlugTitle string
	Title     string
	Body      string
	Tags      []string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.ID,
		arg.SlugTitle,
		arg.Title,
		arg.Body,
		pq.Array(arg.Tags),
	)
	return err
}
